// data/cars.ts
export const DUMMY_CARS_DATA = [
  {
    id: 1,
    name: 'Toyota Camry New',
    year: '2023',
    engine: '3.5 D5 PowerPulse Momentum 5dr AWD',
    miles: '20 Miles',
    fuel: 'Petrol',
    transmission: 'Automatic',
    price: '$40,000',
    badge: 'Great Price',
    image: '/images/dummyCars/car1.png',
  },
  {
    id: 2,
    name: 'T-Cross',
    year: '2023',
    engine: '4.0 D5 PowerPulse Momentum 5dr AWD',
    miles: '15 Miles',
    fuel: 'Petrol',
    transmission: 'Automatic',
    price: '$15,000',
    badge: null,
    image: '/images/dummyCars/car2.png',
  },
  {
    id: 3,
    name: 'Ford Transit',
    year: '2021',
    engine: '4.0 D5 PowerPulse Momentum 5dr AWD',
    miles: '2500 Miles',
    fuel: 'Diesel',
    transmission: 'Manual',
    price: '$22,000',
    badge: 'Great Price',
    image: '/images/dummyCars/car3.png',
  },
  {
    id: 4,
    name: 'Ford Transit',
    year: '2022',
    engine: '4.0 D5 PowerPulse Momentum 5dr AWD',
    miles: '2500 Miles',
    fuel: 'Diesel',
    transmission: 'Automatic',
    price: '$25,000',
    badge: 'Great Price',
    image: '/images/dummyCars/car4.png',
  },
  {
    id: 5,
    name: 'Toyota Camry New',
    year: '2023',
    engine: '3.5 D5 PowerPulse Momentum 5dr AWD',
    miles: '20 Miles',
    fuel: 'Petrol',
    transmission: 'Automatic',
    price: '$40,000',
    badge: 'Great Price',
    image: '/images/dummyCars/car1.png',
  },
  {
    id: 6,
    name: 'T-Cross',
    year: '2023',
    engine: '4.0 D5 PowerPulse Momentum 5dr AWD',
    miles: '15 Miles',
    fuel: 'Petrol',
    transmission: 'Automatic',
    price: '$15,000',
    badge: null,
    image: '/images/dummyCars/car2.png',
  },
  {
    id: 7,
    name: 'Ford Transit',
    year: '2021',
    engine: '4.0 D5 PowerPulse Momentum 5dr AWD',
    miles: '2500 Miles',
    fuel: 'Diesel',
    transmission: 'Manual',
    price: '$22,000',
    badge: 'Great Price',
    image: '/images/dummyCars/car3.png',
  },
  {
    id: 8,
    name: 'Ford Transit',
    year: '2022',
    engine: '4.0 D5 PowerPulse Momentum 5dr AWD',
    miles: '2500 Miles',
    fuel: 'Diesel',
    transmission: 'Automatic',
    price: '$25,000',
    badge: 'Great Price',
    image: '/images/dummyCars/car4.png',
  },
];
